### ISSUE TITLE
Error 'There is no field within the filter' for table 49 on field 'Additional Grouping Identifie'

### ISSUE THREAD

**Issue by rs-tve** [printvis/PrintVis.CloudUpgrade#2]
I am using a Docker container with Business Central 14.39 to practice the Upgrade Tool. When I run page 104000 and click in the Wizard on 'Generate Code for Customization Migration' this error occurs. After investigating the problem I have found the reason for this error. 

The primary key of table 49 is longer than 250 characters!
Codeunit 104000 makes use of table 2000000063 (Key) which has a field 'Key' that can hold a maximum of 250 characters. 

The primary key of table 49 is 251 characters long:
Type,G/L Account,Gen. Bus. Posting Group,Gen. Prod. Posting Group,VAT Bus. Posting Group,VAT Prod. Posting Group,Tax Area Code,Tax Group Code,Tax Liable,Use Tax,Dimension Set ID,Job No.,Fixed Asset Line No.,Deferral Code,Additional Grouping Identifier

**Comment by rikardhult** [comment]
If the table has a longer key the 250 it needs to be upgraded in an other way.
Change the code so the table is skipped, procedure IgnoreField in cu 104000 add
IF TableID = 49 THEN
     EXIT(TRUE);

**Comment by rs-tve** [comment]
Unfortunately the suggested change in CU104000 does not fix the problem.
Change code as shown in picture below.

![Fix to codeunit 104000 to prevent error on table 49](https://user-images.githubusercontent.com/110678314/197140411-540c7ef3-c169-4c0a-89fb-0800f2014e8d.png)
